
from PyQt5.QtWidgets import QApplication,  QWidget
import sys

from Ui_FormWidget import Ui_Form

if __name__ == '__main__':
      app = QApplication(sys.argv)

      window = QWidget()  # we must know the exact class, generated by QtDesigner
      gw = Ui_Form()
      gw.setupUi(window)
      window.show()

      sys.exit(app.exec_())
