
from PyQt5.QtWidgets import QApplication,  QWidget
import sys

from Ui_FormWidget import Ui_Form
#from client_actions import оperation_by_client
#from clients_administration import get_real_client

if __name__ == '__main__':
      app = QApplication(sys.argv)

      w = QWidget()  # we must know the exact class, generated by QtDesigner
      gw = Ui_Form()
      gw.setupUi(w)
      w.show()

#   Input for which one client is all about
#      real_client = get_real_client()
#   What kind of action will be doing
#      оperation_by_client(real_client)

      sys.exit(app.exec_())
